### ISSUE TITLE
Update tests to stop using deprecated lifecycle hooks

### ISSUE THREAD

**Issue by hpohlmeyer** [reactjs/react-transition-group#547] opened 2019-09-04 08:14 UTC
The tests here still use deprecated lifecycle hooks and will fail on upgrading to React 17.

<details>
	<summary>Outdated</summary>

	> What is the current behavior?
	
	React 16.9.x will throws errors for lifecycle methods that will be deprecated.
	https://reactjs.org/blog/2019/08/08/react-v16.9.0.html
	
	Namely:
	
	- componentWillMount
	- componentWillReceiveProps
	- componentWillUpdate
	
	To avoid the errors they can be prefixed with `UNSAFE_` using the provided codemod (`npx react-codemod rename-unsafe-lifecycles`), but they should be replaced in the long run.
	
	> What is the expected behavior?
	
	Using ReactTransitionGroup should not show warnings when used.
</details>

**Comment by iamandrewluca** [comment] 2019-10-08 11:56
@jquense to close as cannot reproduce.

**Comment by hongyuan1306** [comment] 2020-01-10 08:59
With react 16.12.0, I am getting the following warning in Chrome console:

> Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: ReactTransitionGroupPlus

According to the the react migration path under the above link, current code will not work under 17.0:

> 17.0: Remove componentWillMount, componentWillReceiveProps, and componentWillUpdate . (Only the new “UNSAFE_” lifecycle names will work from this point forward.)

Since it is just a simple rename, I think it's time we get it done. 

Thanks.

**Comment by taion** [comment] 2020-01-10 16:48
That's an error in whatever your `ReactTransitionGroupPlus` is, not here.

**Comment by taion** [comment] 2020-01-10 16:50
To be clear this is not actually an issue with the code here. The deprecated lifecycles are used in tests, not in the code.

**Comment by taion** [comment] 2020-01-10 16:53
Actually on second thought I'm just going to close this out for now to avoid potential confusion. We can fix the tests when we upgrade the dev tooling. They're not an issue right now.

**Closed by taion** 2020-01-10 16:53 UTC
