### ISSUE TITLE
"appear" doesn't work for "CSSTransition"

### ISSUE THREAD

**Issue by SoooEZ** [reactjs/react-transition-group#152] opened 2017-08-08 16:47 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
appear={true} doesn't work for "CSSTransition"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

JSX:
```jsx
import React, {Component} from 'react';
import {Link} from 'react-router-dom';
import './StepOne.css';
import CSSTransition from 'react-transition-group/CSSTransition';

export default class StepOne extends Component {

    render() {
        return (
            <CSSTransition
               classNames="fade"
               appear={true}
               timeout={500}>
                <div>
                    <Link to="/type">
                        to step two
                    </Link>
                    <h1>Step One</h1>
                </div>
            </CSSTransition>
        );
    }

}
```
CSS:
```css
.fade-appear {
    opacity: 0.01;
}

.fade-appear.fade-appear-active {
    opacity: 1;
    transition: opacity 500ms ease-in;
}

```

**What is the expected behavior?**
should fade in when refresh or first come to this page.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

I tried V1, it works. I just can't make it work after migrate it to v2. This occur on all browsers, I'm on Mac

**Comment by jquense** [comment] 2017-08-08 17:00
Thanks for the bug report! Can you please provide a working reproduction of the issue via the jsfiddle template, thanks.

**Comment by eric-burel** [comment] 2017-08-10 14:08
This seems to be because you need to mount the transition stuffs before you mount the children. In your example everything is mounted at the same time.
Instead we might need to write an hoc to get this working, for now at least.

**Comment by dleavitt** [comment] 2017-08-20 05:43
Seems like `appear` is not working on `Transition`. Fiddle:
https://jsfiddle.net/dleavitt/rk946r29/14/

**Comment by koba04** [comment] 2017-08-21 04:27
@SoooEZ You should set `in` prop on the `CSSTransition` component.

https://jsfiddle.net/L1f43f5b/

**Comment by hueyhe** [comment] 2017-09-18 02:41
I ran into this problem too. Have this problem solved yet?

**Comment by pritchardtw** [comment] 2017-10-12 03:01
idk if there's any new info but for me it works with an anchor tag but not a link tag.

**Comment by liuhelen10** [comment] 2017-11-02 00:58
I'm also running into this issue, my code looks very similar to @SoooEZ 's. It works when the component is re-mounted after my app is already loaded (i.e. via client-side nav), but when doing a full-page refresh of my app, the animations do not get applied correctly.

I'm currently working around this by forcing `in` to be set to `true` in the next event tick, by using a `setTimeout(() => { this.setState({ in: true }), 0)` in my `componentDidMount`. However, it seems like this should be gracefully handled within `react-transition-group`.

Are there plans to address this in the near future? Also @koba04 it doesn't seem like that JSFiddle is a functional example?

**Comment by koba04** [comment] 2017-11-02 03:49
@liuhelen10 The JSFiddle seems to be broken so I've moved this to codepen.

* https://codepen.io/koba04/pen/ZabMqe?editors=0110

**Comment by liuhelen10** [comment] 2017-11-02 17:36
Thanks for updating that @koba04 !

So my code is quite a bit more complex than that but here is a very simplified version...https://codepen.io/anon/pen/QOyKRy?editors=0110

It appears to be working in the CodePen but I wonder if that's because the CodePen app gets rendered first before the code runs..? Versus when I try it in my app, on a hard page refresh it seems like the app gets mounted AND the animations classnames get applied in the same event tick. I'm basically forcing the classname addition to happen in the next event tick by using the `setTimeout(..., 0)`

Does that make sense? Does this sound like a valid bug to you?

**Comment by koba04** [comment] 2017-11-03 16:25
@liuhelen10 Thanks for creating the CodePen! I've tried the code on my app created by `create-react-app` and it worked fine... I'll try to reproduce the case you mentioned.

**Comment by liuhelen10** [comment] 2017-11-03 17:55
Thank you! Please let me know if you are able to repro :)

**Comment by Tim-ls** [comment] 2017-11-16 02:16
I have the same question

**Comment by oallouch** [comment] 2017-11-16 10:04
Maybe it's the Fiber related issue (React 16).

**Comment by webxzy** [comment] 2017-11-21 18:54
I have the same question too

**Comment by koba04** [comment] 2017-11-22 02:14
Can you create an example to reproduce it?

**Comment by phsantiago** [comment] 2017-12-12 21:41
Working fiddle https://codepen.io/phsantiago/pen/WdNLmm

**Comment by phsantiago** [comment] 2017-12-12 21:42
Working example https://codepen.io/phsantiago/pen/WdNLmm

**Comment by liuhelen10** [comment] 2017-12-14 00:23
@oallouch what's the fiber-related issue?

I'll try to create an example that repros this...I've been unsuccessful so far though.

**Comment by andrewnida** [comment] 2018-01-22 01:49
@liuhelen10 

Would it help to wrap the `Transition` component in a `TransitionGroup`? I discovered when I do this, I can use the `appear` prop as expected. It can be used on the group too to pass down to any children.

Tweak to your example [https://codepen.io/anon/pen/JMzjxo](url)

**Comment by jiachaosun** [comment] 2018-01-29 03:05
@phsantiago 
Thanks your example and that's worked for me.

**Comment by silvenon** [comment] 2018-05-18 15:33
I'm failing to reproduce this. Here's a working example, could someone explain how it fails?

[![Edit jzrxy3n3oy](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jzrxy3n3oy)

**Comment by silvenon** [comment] 2018-05-21 18:39
In the meantime I'll close this. I'll gladly reopen when a demo reproducing the bug is provided.

**Closed by silvenon** 2018-05-21 18:39 UTC

**Comment by zhbhun** [comment] 2018-05-22 03:03
CSSTransition does work, but Transition not, try dleavitt's demo - https://jsfiddle.net/dleavitt/rk946r29/14/.

**Comment by silvenon** [comment] 2018-05-22 22:07
It doesn't work because it doesn't contain the reflow hack, like `CSSTransition` does. [Read the note](http://reactcommunity.org/react-transition-group/transition) right above the example.

**Comment by balalaXD** [comment] 2018-08-21 01:42
In my case
`TypeError: Cannot read property 'appear' of undefined`
because i write the wrong attribute `className="fade"`, instead you should write `classNames="fade"`

**Comment by gauravsoni1** [comment] 2019-03-03 14:39
Same issue for me also, i noticed that it does not work when using create-react-app.

Just trying to run this simple code 
```
<CSSTransition
          in={true}
          appear={true}
          timeout={10000}
          classNames="message"
        >
          <h1>Some text</h1>
        </CSSTransition>
```
```
.message-appear {
  opacity: 0.01;
}
.message-appear-active {
  opacity: 1;
  transition: all 10000ms ease-out;
}
```

**Comment by GeekStocks** [comment] 2019-03-04 07:07
Is `appear` totally busted? While researching my inability to get a **simple page fadein** working I came across [this StackOverflow question](https://stackoverflow.com/questions/31462136/getting-reactcsstransitiongroup-to-work-for-a-fade-in-transition-with-react-js) which at one time appears to have solved someone's problem. It pointed [to this JSFiddle](https://jsfiddle.net/n5Luz6ym/) which is now busted.

I cannot get the [exact React example](https://reactjs.org/docs/animation.html) for `appear` to work. Instead of fading in, test components just render in full opacity at once.

**Comment by jquense** [comment] 2019-03-04 13:59
no, see the above and documentation it works fine.

**Comment by zaxwebs** [comment] 2019-03-13 20:58
Not working for me either.

**Comment by silvenon** [comment] 2019-03-14 13:34
@GeekStocks if you're still having problems, please create a CodeSandbox and explain what your goal is, I'll be very happy to help. 😉

**Comment by pureth** [comment] 2019-03-20 17:32
> 
> 
> Same issue for me also, i noticed that it does not work when using create-react-app.
> 
> Just trying to run this simple code
> 
> ```
> <CSSTransition
>           in={true}
>           appear={true}
>           timeout={10000}
>           classNames="message"
>         >
>           <h1>Some text</h1>
>         </CSSTransition>
> ```
> 
> ```
> .message-appear {
>   opacity: 0.01;
> }
> .message-appear-active {
>   opacity: 1;
>   transition: all 10000ms ease-out;
> }
> ```

here's this example working: 

https://vn3y63zk4l.codesandbox.io/

https://codesandbox.io/s/vn3y63zk4l

**Comment by pmbednarczyk** [comment] 2019-04-06 13:52
Confirming. Doesnt work on CRA

**Comment by silvenon** [comment] 2019-04-06 15:33
@pmbednarczyk please provide an example reproducing the issue. Either CodeSandbox (which uses CRA) or a GitHub repository.

**Comment by vijayst** [comment] 2019-06-28 13:54
Have the same issue. The enter animation on appear is triggered, class names change, but the CSS styles associated with the classes are not getting applied for some reason. I don't have a namespace collision. Not able to reproduce it using CodePen.

**Comment by silvenon** [comment] 2019-06-30 14:06
I wish I had more info, this way it's hard to guess what might have gone wrong. 😕

**Comment by euvl** [comment] 2019-07-15 17:43
tbh seems that the fact that transition does not work with CRA is a red herring. I came to the same conclusion but then realized that "appear" and "enter" transitions are 2 separate things. Documentation does not make it clear that one has to define "appear" transition alongside "enter" transition.

If you would want to use this example http://reactcommunity.org/react-transition-group/css-transition then your transition would look like:

This worked for me:
```
  .my-node-enter, 
  .my-node-appear {
    opacity: 0;
  }

  .my-node-enter-active,
  .my-node-appear-active {
    opacity: 1;
    transition: opacity 200ms;
  }

  .my-node-exit {
    opacity: 1;
  }

  .my-node-exit-active {
    opacity: 0;
    transition: opacity 200ms;
  }
```

**Comment by silvenon** [comment] 2019-07-15 21:05
> transition does not work with CRA

Any demo that proves this would be greatly appreciated 🙏 What do you mean that it doesn't work? What happens?

> Documentation does not make it clear that one has to define "appear" transition alongside (or instead) "enter" transition.

I made and published a couple of changes in the docs to make this info more obvious.

**Comment by ryan-sandy** [comment] 2020-03-30 18:49
For anyone that stumbles over this issue, have to set both `appear` and `in` to be true for the appearance animation to fire.

**Comment by silvenon** [comment] 2020-03-30 19:49
I updated the documentation for `appear` to make this behavior more clear. b58c9575fa1d5627e1537ac46a494d7415c03f96

**Comment by BThvedt** [comment] 2021-03-01 21:13
I had this same issue. I'm using CRA and I made sure 'appear' and 'in' were both true initially ... and entrance animations were not showing when the component first rendered. 
I might be doing it wrong but to fix I manually toggled appear evaluate to 'true' manually right on component load. Basically I used a useState to hold a boolean value and set it to 'true' right after load inside a useEffect. Now the animation I want shows. 
All I needed was 'in'. Making sure 'appear' is there doesn't seem to matter for my case
Maybe that will helps someone. Makes the code a bit messier but I'll live

**Comment by baptisteArno** [comment] 2021-05-21 13:31
@silvenon Here is a reproduction: https://codesandbox.io/s/keen-forest-ghgxq?file=/styles.css:0-343.

As you can see it is displayed right away. I need it to be hidden but still mounted. How do I do this?

**Comment by silvenon** [comment] 2022-02-25 19:29
> As you can see it is displayed right away. I need it to be hidden but still mounted. How do I do this?

@baptisteArno I didn't see this question. Why do you need it to be mounted, but not visible? You can control `opacity` with your own classes, for example if you add an `alert` class to your `<Alert>` component, you could do something like:

```css
.alert:not([class*="alert-enter"]) {
  opacity: 0;
}
```

> Here is a case which does not add *-appear to the children.

`appear` only works when the `in` prop is `true` on component mount. In your case `visible` starts as `false`.

**Comment by cptSwing** [comment] 2024-09-06 13:51
> @LaamGinghong `appear` only works when the `in` prop is `true` on component mount. In your case `visible` starts as `false`.

Jesus that finally made it click for me, spent a day or two trying to figure out why my appear classes would not be applied. Cheers.
