### ISSUE TITLE
Warnings thrown on strictmode

### ISSUE THREAD

**Issue by PerfectionCSGO** [reactjs/react-transition-group#561] opened 2019-10-17 13:40 UTC
> What is the current behavior?
Transition throws a warning in the browser when React.StrictMode is enabled
```
Warning: Received `true` for a non-boolean attribute `in`.

If you want to write it to the DOM, pass a string instead: in="true" or in={value.toString()}.
    in div (created by TransitionGroup)
    in TransitionGroup (created by Gallery)
    in SwitchTransition (created by Gallery)
    in div (created by Gallery)
```

> What is the expected behavior?
Transition should accept a boolean instead of a string.

Reproducable
https://codesandbox.io/embed/strange-field-x3p7e?fontsize=14

I initially made a bug report here but not sure if that was the right place for it. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/38559

**Comment by JonShort** [comment] 2019-10-23 15:36
This seems to be because the `SwitchTransition` component passes the `in` prop down to the child component. In this case, the `TransitionGroup` component renders a `div` by default (so the div thinks that `in` is a HTML attribute).

e.g. this is similar to writing:

```html
<div in={true}>hello</div>
```

This error can be mitigated by adding `component={null}`, so that `TransitionGroup` [doesn't render a wrapper.](https://reactcommunity.org/react-transition-group/transition-group#TransitionGroup-prop-component)

![image](https://user-images.githubusercontent.com/21317379/67407025-c8978a80-f5ae-11e9-9902-14cf6a14e211.png)

---

_However_ I'm not sure that `SwitchTransition` expects as a child of `TransitionGroup`, since it isn't mentioned [in the docs](https://reactcommunity.org/react-transition-group/switch-transition)

![Screenshot 2019-10-23 at 16 05 42](https://user-images.githubusercontent.com/21317379/67407338-4065b500-f5af-11e9-8ddd-9d2359db88d0.png)

---

Hopefully this helps understand why this is happening 👍

**Comment by iamandrewluca** [comment] 2020-03-02 17:50
> Transition throws a warning in the browser when React.StrictMode is enabled

Wrong statement. This warning is thrown by `prop-types`

**Comment by silvenon** [comment] 2020-04-08 17:44
`TransitionGroup` should definitely not be used as a child of `SwitchTransition`, it's probably a hack to achieve a certain behavior. I'm closing this, but let me know what you wanted to achieve and I'll help. 😉

**Closed by silvenon** 2020-04-08 17:44 UTC

**Comment by MorayM** [comment] 2022-08-03 09:34
Hi, I'm seeing this same issue along with the additional error "Unknown event handler property `onExited`. It will be ignored." while using the `onExited` prop on a `CSSTransition` component. I'm not sure if this is a problem with the core library or with @types/react-transition-group? I'm using v4.4.5 of both.

Wrapping the `CSSTransition` in `<TransitionGroup component={null}>` doesn't fix it.

**Comment by silvenon** [comment] 2022-08-03 14:36
> "Unknown event handler property onExited. It will be ignored."

This is not a type error, it sounds like you added an `onExited` prop to a regular element, so React is letting you know that the event doesn't exist, so it's ignoring that prop. Check your code, I don't think it's related to `react-transition-group`. You can show your code if you're unable to find it.

**Comment by silvenon** [comment] 2022-08-03 14:39
> I'm seeing this same issue

As for this, are you also using `TransitionGroup` as a direct child of `SwitchTransition`?

**Comment by MorayM** [comment] 2022-08-03 14:56
See the component in question below. `onExited` is on the `CSSTransition` component. It was previously just a `CSSTransition` component on its own as per [this example](http://reactcommunity.org/react-transition-group/css-transition), but I added the `TransitionGroup` element after seeing this ticket. Unfortunately I haven't been able to recreate it in a sandbox - it's part of a huge project.

```typescript
const Message = (props: MessageProps) => {
  const [open, setOpen] = useState(true);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;

    // Set height for fade out transition
    const setHeightRef = () => {
      if (ref.current) {
        ref.current.style.height = '';
        ref.current.style.height = `${ref.current.clientHeight}px`;
      }
    };

    setHeightRef();
    window.addEventListener('resize', setHeightRef);

    // eslint-disable-next-line consistent-return
    return () => {
      window.removeEventListener('resize', setHeightRef);
    };
  });

  return (
    <TransitionGroup component={null}>
      <CSSTransition
        in={open}
        timeout={1200}
        classNames={{
          enter: classes.enter,
          exit: classes.exit,
          exitActive: classes.exitActive,
        }}
        unmountOnExit={true}
        onExited={() => {
          console.log('exited');
        }}
      >
        <div
          ref={ref}
          className={`messageWrap ${classes.wrap} ${classes[props.type]} ${props.className ? props.className : ''}`}
        >
          <div className={classes.outer}>
            <div className={classes.inner}>
              <div>
                Hello world
              </div>
              <div className={classes.iconWrap}>
                {props.type !== 'default' && <CrossCircleIcon onClick={() => {
                  setOpen(false);
                }} />}
              </div>
            </div>
          </div>
        </div>
      </CSSTransition>
    </TransitionGroup>
  );
};
```

**Comment by silvenon** [comment] 2022-08-03 17:07
> Unfortunately I haven't been able to recreate it in a sandbox

I hope you'll eventually manage to reproduce the warning, I'm not sure what could be the problem here.

By the way, unrelated to the problem, editing inline styles the way you do is a bit problematic, I recommend using state. You can do this by extracting `.messageWrap` div into its own component, and moving the `useEffect` there. There you can set the height via state and not have to worry about re-rendering everything.
