### ISSUE TITLE
Cannot import CSSTransition from react-transition group

### ISSUE THREAD

**Issue by manan30** [reactjs/react-transition-group#461] opened 2019-02-22 15:14 UTC
Hello, I amhaving this issue while importing CSSTransition and TransitionGroup from react-transition-group. Can somebody please help? Thanks!

```
TypeError: Cannot read property 'isRequired' of undefined
eval
node_modules/babel-loader/lib/index.js??ref--6-oneOf-2!/Users/numpj2/Spaces/Projects/deli-ui/node_modules/react-transition-group/CSSTransitionGroupChild.js:104
  101 | 
  102 | var propTypes = {
  103 |   children: _propTypes2.default.node,
> 104 |   name: _PropTypes.nameShape.isRequired,
  105 |   // Once we require timeouts to be specified, we can remove the
  106 |   // boolean flags (appear etc.) and just accept a number
  107 |   // or a bool for the timeout flags (appearTimeout etc.)
```

**Comment by silvenon** [comment] 2019-02-23 10:46
Probably a duplicate of #440.

**Closed by silvenon** 2019-02-23 10:46 UTC
