### ISSUE TITLE
enter and enter-active applied simultaneously

### ISSUE THREAD

**Issue by rr-kalbeck** [reactjs/react-transition-group#246] opened 2017-11-07 11:36 UTC
with CSSTransition it seems enter and enter-active are applied simultaneously. is that correct? which means the following doesn't work..

```
div {
    transition: opacity 1s;

    &.fade-enter {
        opacity: 0;
    }

    &.fade-enter-active {
        opacity: 1;
    }
}
```

and instead must be..

```
div {
    transition: opacity 1s;

    &.fade-enter {
        opacity: 0.01;
    }

    &.fade-enter-active {
        opacity: 1;
    }
}
```

with ng-animate starting at `opacity: 0` works, i'm guessing angular applies enter-active after enter ie- next tick. would it be possible to do the same?

**Comment by jquense** [comment] 2017-11-07 12:16
The active classes are added on the next tick, opacity: 0 works in my tests (generally that's what I use)

**Comment by liorgreenb** [comment] 2017-11-22 10:58
I confirm that this happens to me too

**Comment by jquense** [comment] 2017-11-22 13:56
can you provide a repro?

**Comment by liorgreenb** [comment] 2017-11-22 14:43
I'll try to make one, meanwhile i made a workaround using animation on enter class

**Comment by helixbass** [comment] 2017-12-05 18:37
This is also happening to me (for an `appear` on a `CSSTransition`) - if I wrap the call to `this.props.onEntering(node, appearing)` in a `setTimeout(..., 50)`, the enter/appear transition works as expected

In a project using `react@15.6.1`, testing in Chrome

**Comment by alyrik** [comment] 2017-12-22 13:51
I can confirm that it happens during the same tick in a case when animated content has an input with `autoFocus` prop.

**Comment by Adrxx** [comment] 2018-02-16 21:58
Try not adding the transition property to the appear/enter classes, it should only be on the appearActive/enterActive classes, that worked for me ;)

**Comment by teameh** [comment] 2018-04-19 11:53
@Adrxx that indeed fixes the issue for me. @rr-kalbeck see the codesandbox example from the docs. https://codesandbox.io/s/00rqyo26kn?module=%2Fstyles.css

**Doesn't always work:**
```
.fade {
  transition: opacity 500ms ease-in;
}
.fade-enter {
  opacity: 0.01;
}
.fade-enter-active {
  opacity: 1;
}
```

**Better:**

```
.fade-enter {
  opacity: 0.01;
}
.fade-enter-active {
  opacity: 1;
  transition: opacity 500ms ease-in;
}
```

**Comment by silvenon** [comment] 2018-04-19 17:14
Can you provide a demo for this issue? It should always work, if you add a `className` to the `CSSTransition` or its immediate child, it should stay on the entire time.

**Comment by teameh** [comment] 2018-04-23 08:29
Well you can see it in the docs example not staying on the entire time right? https://codesandbox.io/s/00rqyo26kn

**Comment by silvenon** [comment] 2018-04-23 14:14
Please be more specific. In our example `fade` class is never applied, the prop `classNames` (with the "s") defines that all transition-related classes should start with `fade-`. The `list-group-item` class of the `<ListGroupItem>` component stays on the whole time, `fade-*` classes are always _appended_ to it, they never replace it.

**Comment by teameh** [comment] 2018-04-23 15:56
Sorry I misunderstood. I misread `className` for `classNames` in:

> Can you provide a demo for this issue? It should always work, if you add a `className` to the `CSSTransition` or its immediate child, it should stay on the entire time.

So I thought you meant the `fade` class (not `fade-*`) should stay on the entire time if you provide it with `classNames`. Does that explain my  https://github.com/reactjs/react-transition-group/issues/246#issuecomment-383496078  ?

> In our example fade class is never applied, the prop classNames (with the "s") defines that all transition-related classes should start with fade-. The list-group-item class of the <ListGroupItem> component stays on the whole time, fade-* classes are always appended to it, they never replace it.

Yeah that's clear now, thanks :) 

> Please be more specific, what's actually happening vs. what you're expecting. 

I think the  OP expected something like this to work:

https://codesandbox.io/s/k0m40953mo?module=%2Fstyles.css

```
.item {
  transition: opacity 500ms ease-in;
}
.fade-enter {
  opacity: 0.01;
}
.fade-enter-active {
  opacity: 1;
}
```

Which indeed works in the isolated example, but did not work in my project. When mounting a big Modal it did not fade in the first time (it did fade in and out unmounting and re-mounting it a second time). I tried to isolate the problem but I can't reproduce it in the code sandbox.

Putting the transition on the `fade-enter-active` instead fixed the issue for me. I can't figure out why.

**Comment by silvenon** [comment] 2018-04-23 17:28
> So I thought you meant the fade class (not fade-*) should stay on the entire time if you provide it with classNames. Does that explain my https://github.com/reactjs/react-transition-group/issues/246#issuecomment-383496078?

Yep! ⭐️ I see where the misunderstanding was, we should make that more clear in the docs, because it's easy to mistake `classNames` for `className`.

If you have that project available somewhere I can check it out.

**Comment by silvenon** [comment] 2018-04-23 17:30
Closing this until a repro is provided. But I'll be happy to help with your specific issue @teameh.

**Comment by teameh** [comment] 2018-04-24 08:46
No worries. My issue was solved by applying the transition to the `active` class.

**Closed** 2018-04-24 18:38 UTC

**Comment by SkutinAnton** [comment] 2019-12-30 08:38
My decision:
  
```
.enter {
    transform: translateY(-10px);
    opacity: 0;
    transition: 0.4s; <---- delete here
  }

  .enter-active {
    transform: translateY(0);
    opacity: 1;
    transition: 0.4s; <---- put here
  }
```

**Comment by silvenon** [comment] 2020-04-01 00:03
@SkutinAnton yep, this is the correct conclusion, I edited the docs to make this more clear. 5c186f1ec96bbe1eec0c5d5c2d514731adbddc01 In your case `.enter` defines initial styles, which should be applied immediately because `.enter-active` is applied on the next tick, i.e. immediately afterwards. Full explanation below:

---

The reason why you should define `transition` only for `*-active` classes is because `*-enter`/`*-exit` classes define which styles you're starting from, so you'll usually want these styles to be applied _immediately_. If you have `transition` defined at all times, this could cause transitions to misbehave if they're not _symmetrical_, depending on your goal, and by "not symmetrical" I mean that styles in `*-enter-active`/`*-enter-done` are not the same as `*-exit`, and/or styles `*-exit-active`/`*-exit-done` are not the same as `*-enter`.

When they are symmetrical, there is usually no problem because the issue is hidden, let's describe the timeline for a simple fading transition when the CSS property `transition` is being defined at all times:

1. `*-enter` is applied, the component starts transitioning to `opacity: 0`
2. `*-enter-active` is applied on the next tick, the component immediately starts transitioning to `opacity: 1`, essentially ignoring `*-enter` because it didn't have time to transition
    - this is not a problem if `*-exit-active`/`*-exit-done` is the same as `*-enter`, but if it isn't you might want a different behavior
3. `*-enter-done` is applied, the component stays at `opacity: 1`
4. `*-exit` is applied, the component continues from `opacity: 1`
5. `*-exit-active` is applied on the next tick, the component immediately starts transition to `opacity: 0`
    - this is not a problem here because `*-enter-done` is the same as `*-exit-active`, but if it isn't you might want a different behavior

I hope it's more clear now 😄

**Comment by madhuni** [comment] 2020-05-16 03:55
@silvenon, thanks for the explanation.

But I am finding a wearied behaviour with `CSSTransition`, `*-enter` class is never applied to the element and `*-enter-active` is applied directly.

Due to this very reason, my initial style defines in `*-enter` is never getting applied. On the other hand `*-end` class is getting applied properly.

Can somebody help me with this issue?

**Comment by silvenon** [comment] 2020-05-16 07:03
That’s incorrect behavior, please provide a repro so we can help and open a new issue because it’s not related to this one.

I assume that you’re changing the transitioning element mid-transition, probably accidentally if you didn’t expect this, but I have to see the repro to know for sure.
